[package]
name = "xtask"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libftd2xx = "0.32.1"
structopt = "0.3.26"
xshell = "0.2.2"
