[package]
name = "teachee-desktop"
version = "0.1.0"
edition = "2021"

[features]
mock_usb = []

[dependencies]
eframe = "0.19.0"
libftd2xx = "0.32.1"

[workspace]
members = [
    ".",
    "xtask",
]
