[package]
name = "teachee-desktop"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.20.1"
tracing-subscriber = "0.3.16"

[workspace]
members = [
    ".",
    "xtask",
]
