on:
  pull_request:
    branches: [ main ]

name: Lint SystemVerilog Code

jobs:
  svlint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: raftario/setup-rust-action@v1
      - run: cargo install svlint && SVLINT_CONFIG=rtl/.svlint.toml svlint rtl/axis/*.sv rtl/ft232h/*.sv rtl/xadc/*.sv rtl/examples/*/*.sv 